# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='name',
            field=models.CharField(default='nothing there yet', max_length=255),
            preserve_default=False,
        ),
    ]
